### ISSUE TITLE
non-utm + non-aligned coords: x-aligned offset error

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#104]
When working in EPSG:3035, and requesting area that is not rounded to 10m, error happens.

**Comment by EmileSonneveld** [comment]
Could reproduce by modifying `testCreoNonNativeProjection()`
`java.lang.IllegalArgumentException: requirement failed: x-aligned: offset by CellSize(10.0,10.0) 0.9`

**Comment by EmileSonneveld** [comment]
Related: https://github.com/locationtech/geotrellis/issues/3292
