### ISSUE TITLE
upgrade to spark 3.3

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#109]

**Comment by bossie** [comment]
Release notes for Spark 3.3.1: https://spark.apache.org/releases/spark-release-3-3-0.html

This build runs fine: https://jenkins.vgt.vito.be/job/openEO/job/openeo-geotrellis-extensions/job/109-upgrade-to-spark-33/

SLF4J should just pick up the Log4j 2.x that Spark provides; there should be no code changes in this case but we'll probably have to update its configuration: https://logging.apache.org/log4j/2.x/manual/configuration.html

The openeo-logging artifact currently builds against Spark 3.2's Log4j 1.x so that will bomb at runtime; Log4j 2.x has JSON support out of the box so we can probably get rid of this artifact altogether: https://logging.apache.org/log4j/2.x/manual/json-template-layout.html

Impact (of upgraded dependencies) on embedded tsservice: to be investigated.

**Comment by bossie** [comment]
Next step: bumping the version and run openeo-geopyspark-driver tests against the new jar: https://github.com/Open-EO/openeo-geotrellis-extensions/blob/ee33ce2cd98e9b394863ab21a3f9093f27b1ef24/Jenkinsfile#L98

Future step: branch off our Docker image building repos and create a Docker image with the new Spark in it.

**Comment by bossie** [comment]
As discussed: I believe it would have been possible to exclude this Spark's dependency on Log4j 2.x and include Log4j 1.x ourselves to avoid having to update logging configuration and JSON output but we'll take this chance to upgrade to Log4j 2.x instead.

**Comment by bossie** [comment]
`org.openeo:geotrellis-extensions:2.3.0_2.12-spark331` has been published to Artifactory (in libs-release-public instead of libs-snapshot-public but ok).

openeo-geoypyspark-driver runs its tests in a [vito-docker.artifactory.vgt.vito.be/almalinux8.5-spark-py-openeo:3.2.0 container](https://github.com/Open-EO/openeo-geopyspark-driver/blob/f9d7f93e0d611c51d6242d7cc198d1cc3d86f6ce/Jenkinsfile#L27) against [the Spark 3.3.1 jars](https://github.com/Open-EO/openeo-geopyspark-driver/blob/f9d7f93e0d611c51d6242d7cc198d1cc3d86f6ce/scripts/get-jars.py#L65-L67).

**Comment by bossie** [comment]
[Added a pipeline](https://github.com/Open-EO/openeo-geotrellis-kubernetes/commit/5cea29be9919e57e2db45c40a701fad32a3bae72) for image vito-docker.artifactory.vgt.vito.be/almalinux8.5-spark-py-openeo:3.3.1.

**Comment by bossie** [comment]
For reference: the `openeo-yarn` Docker image hierarchy:

1. `openeo-geotrellis-kubernetes/docker/AlmaLinux/Dockerfile.almalinux8.5-spark-py-openeo`
2. `openeo-geotrellis-kubernetes/docker/AlmaLinux/Dockerfile.openeo-base`
3. `openeo-deploy/mep/Dockerfile`

**Comment by bossie** [comment]
openeo-geopyspark-driver [successfully ran tests](https://jenkins.vgt.vito.be/job/openEO/job/openeo-geopyspark-driver/job/upgrade-to-spark-33/11/) against [Spark 3.3.1 geotrellis-extensions jars](https://github.com/Open-EO/openeo-geopyspark-driver/blob/9a3e07216bb8f67578a6c7e66702d4fb46b9a0b2/scripts/get-jars.py#L65-L67) in a [Spark 3.3.1 Docker image](https://github.com/Open-EO/openeo-geopyspark-driver/blob/9a3e07216bb8f67578a6c7e66702d4fb46b9a0b2/Jenkinsfile#L27). :partying_face: 

Had to [adapt jenkinslib](https://git.vito.be/projects/BIGGEO/repos/jenkinslib/commits/7a0acf83e2df1444d2e9a825cf33be2a0731078c#resources/python/test.sh) to work around hard-coded references to Spark 3.2.0.

**Comment by bossie** [comment]
As expected, there are [no Java logs in Kibana](https://kibana-infra.vgt.vito.be/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-08T23:00:00.000Z',to:'2023-02-09T23:00:00.000Z'))&_a=(columns:!(message,filename),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',key:job_id,negate:!f,params:(query:j-598b29d39b46451c992729b095456fe5),type:phrase),query:(match:(job_id:(query:j-598b29d39b46451c992729b095456fe5,type:phrase))))),index:'907d8590-4f1b-11ed-8cc4-3747d5233c59',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))) in the context of a batch job in this Spark 3.3.1 deployment, neither for the [web app](https://epod-master2.vgt.vito.be:8090/cluster/app/application_1674538064532_57849) nor the [batch job](https://epod-master2.vgt.vito.be:8090/cluster/app/application_1674538064532_57892).

**Comment by bossie** [comment]
The web app on Terrascope picks up the configuration in log4j2.xml (output of `-Dlog4j2.debug=true`):

> 2023-02-14 09:48:45,913 main ERROR Console contains an invalid element or attribute "JsonTemplateLayout"
2023-02-14 09:48:45,930 main ERROR File contains an invalid element or attribute "JsonTemplateLayout"

The `JsonTemplateLayout` class was in the `geotrellis-extensions` jar so it seems we still cannot do without an additional `openeo-logging` artifact. We might as well put the OpenEOJsonLogLayout.json file in that artifact and reference it from log4j2.xml with "`classpath:`" as well then.

**Comment by bossie** [comment]
Had to implement some workarounds with regards to versions to not interfere with ongoing development; these can be addressed when we merge.

**Comment by bossie** [comment]
Did the merge.

Judging from the integration tests, YARN deployment looks ok: web app and batch jobs run in Spark 3.3.1 and they still emit Java logs; async_task still emits Java logs as well.

Web app and batch jobs on CreoDIAS also run in Spark 3.3.1 and still emit Java logs. :partying_face:

**Comment by bossie** [comment]
TODO:

- [x] delete relevant Jenkins jobs
- [x] ~delete relevant branches?~
- [x] remove job_tracker and async_task Nifi flows
- [x] remove `-Dlog4j2.debug=true` to reduce clutter in the logs
- [x] remove log4j.properties superseded by log4j2.xml everywhere
- [x] document upgrade procedure (repositories touched, how to build RPM etc)

**Comment by bossie** [comment]
So the upgrade basically came down to this:

- build and test `openeo-geotrellis-extensions` against Spark 3.3.1 dependencies; push the resulting jars to Artifactory;
- do the same for `geotrellistimeseries`;
- run the Snowflakes/spark3 Jenkins job to generate a spark-bin RPM with Spark 3.3.1
- adapt `openeo-geotrellis-kubernetes` to generate new almalinux8.5-spark-py-openeo (with the new RPM), openeo-base and openeo-geotrellis-kube images;
- build and test `openeo-geopyspark-driver` against new pyspark and new jars in new almalinux8.5-spark-py-openeo container;
- adapt `openeo-deploy` to generate new openeo-yarn image and run integration tests against them;
- adapt `os_creodias_openeo_k8s` to apply Log4j2 configuration;

**General**: introduce branches across the board that create artifacts with specific versions to not interfere with existing development (in terms of source code and artifacts), then adapt `jenkinsjobbuilder` to build these branches.
