### ISSUE TITLE
mask_scl_dilation: refactor to create the full mask first, for consistency

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#121]
mask_scl_dilation often has issues on tile edges, because clouds in neighbouring products are not visible.
This was solved by the large overlap in Sentinel-2 products, but returns as an issue when loading with large tile sizes.

I propose to first build the entire mask, then apply it using the regular masking procedure. This has most chances of ensuring consistency.

**Comment by JeroenVerstraelen** [comment]
@jdries When we construct the entire mask this will also have to be done in tiles. How is this different from the current implementation? It seems like the same issues will arise.

**Comment by JeroenVerstraelen** [comment]
I did several tests where with a tilesize of 2048 and the new approach solves the issues at the tile borders:

_Current_
![Image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/200c6f2e-fcb9-4756-86ed-64c5348f6cc8)
_New_
![Image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/c923f9ef-a6f6-45e9-8afe-90c40bb45544)

In the top right of the first image you can see that the mask is clearly cut off by the tile borders. In the second image this border is no longer present and the dilated clouds of the neighbouring tiles have removed much of that mask.

**Comment by jdries** [comment]
@JeroenVerstraelen  what's the setting to enable this? 
We should also make an assessment of performance impact. Can be done by looking at cpu use, but also spark-UI inspection.

**Comment by jdries** [comment]
I get an issue on the output edge still, this is my code for the mask:
```

scl = connection.load_collection(
            S2_collection,
            bands=["SCL"],
            spatial_extent=bbox,
            temporal_extent=[start, end],
            max_cloud_cover=95
        ).resample_spatial(projection=target_crs, resolution=10.0)
        mask = scl.process(
            "to_scl_dilation_mask",
            data=scl,
            kernel1_size=17, kernel2_size=77,
            mask1_values=[2, 4, 5, 6, 7],
            mask2_values=[3, 8, 9, 10, 11],
            erosion_kernel_size=3)
        bands = bands.mask(mask)
```


![Image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/5937096/3f2d237e-2557-4b26-9e75-041611266cca)

**Comment by JeroenVerstraelen** [comment]
@jdries is it possible to get the full code with bbox and temporal extent?
I used what I think is your process graph from the CDSE logs but the result appears to be correct. 

This is the code I'm currently using:
```
bbox = {'west': 3740000.0, 'south': 3020000.0, 'east': 3740150.0, 'north': 3020150.0, 'crs': 'EPSG:3035'}
bands = ["B08", "SCL"]
start = "2021-03-01"
end = "2021-10-31"
S2_collection = "TERRASCOPE_S2_TOC_V2"
connection = openeo.connect("https://openeo-dev.vito.be/openeo/1.0").authenticate_oidc()
target_crs = "EPSG:3035"

s2 = connection.load_collection("TERRASCOPE_S2_TOC_V2", spatial_extent = bbox, temporal_extent = [start, end],
    bands = bands).resample_spatial(projection = target_crs, resolution = 10.0)

scl = connection.load_collection(
            S2_collection,
            bands=["SCL"],
            spatial_extent=bbox,
            temporal_extent=[start, end],
            max_cloud_cover=95
        ).resample_spatial(projection=target_crs, resolution=10.0)
mask = scl.process(
    "to_scl_dilation_mask",
    data=scl,
    kernel1_size=17, kernel2_size=77,
    mask1_values=[2, 4, 5, 6, 7],
    mask2_values=[3, 8, 9, 10, 11],
    erosion_kernel_size=3)
masked = s2.mask(mask)
masked.download("mask_scl_dilation.nc")
```

**Comment by JeroenVerstraelen** [comment]
When using a large area I get these results:
mask_scl_dilation (current):
![Screenshot from 2023-06-22 15-51-41](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/972c9821-79fb-43e3-987f-1a4f4a00403d)

to_scl_dilation_mask (new):
![Screenshot from 2023-06-22 15-51-53](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/17163723-7310-4055-92f7-74453194d4e6)

Overlayed:
![Screenshot from 2023-06-22 16-00-05](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/535549f3-fe62-40f3-914f-12a1fb6e1fc4)

So it looks like:
-  The current process is more aggressive than the new process
-  Everything that has been masked by the new process was also masked by the current one, they align perfectly.
-  The new process masked away some of the south and east edges, while the current process didn't.

**Comment by JeroenVerstraelen** [comment]
For a far larger extent they appear to be almost identical:

current:
![Screenshot from 2023-06-22 16-27-15](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/bb0acc9b-74b6-4c12-b48c-7b5d2d8f3f29)

new:
![Screenshot from 2023-06-22 16-26-52](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/2a005794-98e6-4848-afe8-5b17248f58de)

overlay (current in red):
![Screenshot from 2023-06-22 16-28-42](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/b30cb35a-319b-4de8-aa49-0ed23a7fefd3)

There is only a slight difference at the edge where the current process (red) masked away more than the new one (black):
![Screenshot from 2023-06-22 16-29-47](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/0b0c3510-ff83-4e99-98b8-2c8533ac9957)

**Comment by jdries** [comment]
@JeroenVerstraelen  the problem is also visible in your code, but note that QGis does not show these nodata pixels at the edge.
When I enlarge the bbox of the mask, the problem goes away.
I think we need to do something like this:
https://github.com/Open-EO/openeo-python-driver/blob/779b690183932f5f4acb84925167bb6306f8f44f/openeo_driver/dry_run.py#L617
To ensure that load_collection is aware that a pixel buffer is needed.

**Comment by jdries** [comment]
added a commit to get fix going. The buffer is normally applied here:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/7e8521ce39b6f82f7526cbdce4b49f48842cb410/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala#L621

**Comment by jdries** [comment]
works better now, I only still see a one pixel difference on the mask boundary when working on a very small (15x15 pixel)  area.
