### ISSUE TITLE
apply Sentinel-2 scale + offset for new products

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#144]
Sentinel-2 L2A products processed with latest version have a scale and offset that needs to be applied, otherwise users will get unexpected results.

> Please note that starting with 25th January 2022 (PB 04.00), to allow encoding negative surface reflectances that may occur over very dark surfaces, the dynamic range of Level-2A products is shifted by a band-dependent constant BOA_ADD_OFFSET. The value of this offset is available in the product metadata.

The default offset seems to be -1000 for all bands, but need to check product baseline.

**Comment by EmileSonneveld** [comment]
@jdries Where should the scaling happen? 
I checked behind `connection.load_collection("SENTINEL2_L2A", ...` that in it's turn loaded [this URL](https://services.terrascope.be/catalogue/products?collection=urn%3Aeop%3AVITO%3ATERRASCOPE_S2_TOC_V2&bbox=5.1390519%2C51.1693853%2C5.1710393%2C51.1906245&sortKeys=title&startIndex=1&accessedFrom=MEP&clientId=r-6de8dd93d56d416c8d1b20699bc8028b_0&start=2023-04-04T00%3A00%3A00Z&end=2023-04-06T23%3A59%3A59.999999999Z), but there is no BOA_ADD_OFFSET here.

**Comment by jdries** [comment]
no, because that loads from terrascope, which has the offset already applied. The problem only occurs on creodias/CDSE.
You can use the new copernicus dataspace website to look for an example product.

**Comment by EmileSonneveld** [comment]
The scala code now gives the same values as in Terrascope:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/bfac98c2-e4a0-497c-9e1b-27a6aa5c6c37)

**Comment by EmileSonneveld** [comment]
Documentation about offset moved:
https://sentinels.copernicus.eu/-/copernicus-sentinel-2-major-products-upgrade-upcoming
