### ISSUE TITLE
support bands with 10m and 20m resolution in single datacube (Sentinel-2)

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#152]
Currently, a MultibandTile consists of tiles with the same resolution.
Sentinel-2 however has bands in 10m and 20m resolution. 
We have 2 cases to try and keep bands in 20m:
- super-resolution use case requiring bands in original format
- reduce memory use & increase processing performance

**Comment by jdries** [comment]
Proposed solution: create Tile implementation that looks like 10m, but uses downsampled array for storage.

**Comment by JeroenVerstraelen** [comment]
The feature is live on the development servers and can be tested using:
```
connection: Connection = openeo.connect("https://openeo-dev.vito.be/openeo/1.0").authenticate_oidc()
sentinel2_data_cube: DataCube = connection.load_collection("TERRASCOPE_S2_TOC_V2",
    temporal_extent = ["2018-05-06", "2018-05-06"], bands = ["B02", "B05", "B08"], spatial_extent = {
        'west': 5.15183687210083,
        'east': 5.153381824493408,
        'south': 51.18192559252128,
        'north': 51.18469636040683,
        'crs': "EPSG:4326"
    })
sentinel2_data_cube.result_node().update_arguments(featureflags={'no_resample_on_read': True})
```

There are still some issue with the gridbounds calculations.
```
openeo.rest.OpenEoApiError: [500] Internal: Server error: Exception during Spark execution: GridBounds(0,0,-1,15) do not intersect 7x16 (ref: r-d12ea993bd844226b32901e1a229be85)
```

**Comment by JeroenVerstraelen** [comment]
The issue has been solved and tested on openeo-dev.
