### ISSUE TITLE
handle gdal error on creo

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#157]
@JeroenVerstraelen  we added a retry forever already, but can you add a java system property that allows us to control number of retries?
Other option would be using config file, but not sure if there's sufficient things in place to access those config values in scala?

**Comment by jdries** [comment]
@JeroenVerstraelen  I recently also discovered this option:
GDAL_HTTP_MAX_RETRY
Perhaps, for this issue, we can reduce amount of retries in our code, and try to add using this setting, which is already configurable.
Stability on CF should also be better now.

**Comment by JeroenVerstraelen** [comment]
Number of retries is now configurable using an environment variable. I will take a look at GDAL_HTTP_MAX_RETRY.

**Comment by JeroenVerstraelen** [comment]
@jdries Since the implementation using environment variables is already complete and live on staging, should I still look into GDAL_HTTP_MAX_RETRY?

**Comment by JeroenVerstraelen** [comment]
In the meantime I will reduce the default max retries from 50 to 10 and do the same on cdse-staging.

**Comment by jdries** [comment]
yes, maybe it's good to configure GDAL_HTTP_MAX_RETRY explicitly, this gives operations people a clear view on relevant tunables.
