### ISSUE TITLE
sample_by_features: result too large

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#159]
https://discuss.eodc.eu/t/filter-spatial-create-datacubes-which-are-wider-than-the-input-polygons/581/2

**Comment by JeroenVerstraelen** [comment]
New implementation has been tested, it solved the issue of uncropped tiles for datacubes with a time dimension:

_Old implementation:_
![sampleByFeatureOld](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/e6d485ef-c716-4e4f-9081-3bcd6d612399)

_New implementation:_
![sampleByFeatureNew](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/3028262/b52fec1a-b849-4a92-b4f9-721a23c3a44c)
