### ISSUE TITLE
lack of dependencies when compiling

### ISSUE THREAD

**Issue by geostax** [Open-EO/openeo-geotrellis-extensions#16]
Hi,
I found it was hard to find those dependencies. How can i get them?
 ```xml
<dependency>
            <groupId>be.vito.eodata.gwc-geotrellis</groupId>
            <artifactId>gwc-geotrellis-core</artifactId>
            <version>0.7.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>org.locationtech.geotrellis</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.scala-lang</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.azavea.geotrellis</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <artifactId>ExtractTimeSeries</artifactId>
            <groupId>be.vito.eodata</groupId>
            <version>${geotrellistimeseries.version}</version>
            <scope>runtime</scope>
        </dependency>
```

**Comment by jdries** [comment]
I would recommend building the develop branch, I recently removed the dependency on 'ExtractTimeSeries'.
I could not yet remove gwc-geotrellis, so pushed that to a public repo:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/tree/General/libs-snapshot-public/be/vito/eodata/gwc-geotrellis/gwc-geotrellis-core/0.7.0-SNAPSHOT/gwc-geotrellis-core-0.7.0-20200907.073222-7.jar

As a better solution, I'll either push that entirely to a public open source repo, or remove the dependency.

**Comment by jdries** [comment]
Note: the dependency on gwc-geotrellis is very loose. So in fact, you can even remove it entirely.
It is only used in this integration test:
org.openeo.geotrellis.integrationtests.WMTSServletTest
Which will not run anyway and is ignored. So you can delete that test, and the dependency, and the jar should built.

Maybe I can further improve this by having a separate maven build that includes this internal dependency.

**Comment by geostax** [comment]
OK, thanks. It is very helpful
