### ISSUE TITLE
Sentinel2 L1C: SAA SZA VAA VZA bands not found

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#177]
Probably here, changing finder.creodias.eu to zipper.creodias.eu could solve the problem.
Also filtering out the prefixes could be nicer.

https://github.com/Open-EO/openeo-geotrellis-extensions/blob/68143219e6882dffd0d05a46aaf29e530c0b93a5/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/FileLayerProvider.scala#L884

Example error from kibana:
```
java.net.MalformedURLException: no protocol: /eodata/Sentinel-2/MSI/L1C/2023/05/30/S2B_MSIL1C_20230530T104629_N0509_R051_T31UFS_20230530T125255.SAFE/GRANULE/L1C_T31UFS_A032538_20230530T104623/MTD_TL.xml
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at org.openeo.geotrellis.layers.FileLayerProvider.rasterSource$1(FileLayerProvider.scala:947)
	at org.openeo.geotrellis.layers.FileLayerProvider.$anonfun$deriveRasterSources$21(FileLayerProvider.scala:1011)
```

The error is about the prefix, but even without the good prefix, the url gives a 404: https://finder.creodias.eu/files/Sentinel-2/MSI/L1C/2023/05/30/S2B_MSIL1C_20230530T104629_N0509_R051_T31UFS_20230530T125255.SAFE/GRANULE/L1C_T31UFS_A032538_20230530T104623/MTD_TL.xml

**Comment by jdries** [comment]
also check state of these bands SENTINEL2_L2A

**Comment by EmileSonneveld** [comment]
This works now on CDSE and tests are added as to `test_collections.py` https://git.vito.be/projects/TPT/repos/os_creodias_openeo_k8s/browse/kube_resources/applications/integrationtests/tests/test_collections.py?at=797c76d2003343dbd42427fa8591c2777a1219ab#120-121

Also tested with example from Pratichhya: [pratichhya_angle_bands.json.txt](https://github.com/Open-EO/openeo-geotrellis-extensions/files/12596970/pratichhya_angle_bands.json.txt)

However, on `openeo.vito.be` this does not work atm.

**Comment by EmileSonneveld** [comment]
On openeo.vito.be those bands work: `"relativeAzimuthAngles", "sunZenithAngles", "viewZenithAngles"`
The sunZenithAngles has the same color distribution on both platforms:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/dc7e10c4-3883-4c52-8d67-1d59bbafee58)

**Comment by EmileSonneveld** [comment]
This seem to work for simple graphs using angle bands, but when running this larger example, there is still an extent error:
https://github.com/jdries/worldwater-toolbox/blob/vito/tests/test_openeo_integration.py#L54

**Comment by EmileSonneveld** [comment]
The graph from `test_multiple_months()` ran successfully locally on branch `band_with_different_resolution`:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/1d48e519-40d0-4692-b63f-7fd0d9d4321c)

**Comment by EmileSonneveld** [comment]
Also tested on https://openeo.dev.warsaw.openeo.dataspace.copernicus.eu/ `j-7113dc80887c47f08b04fc096954fdc1`
