### ISSUE TITLE
Numerical errors when calculating SD?

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#225]
Looks like some floating point errors, or integer overflow.
```python
.aggregate_temporal(intervals=temporal_extent, labels=[temporal_extent[0]], reducer="sd", dimension="t")
```
job_id: `j-23110872a30f419fb4ace82d03c2cbc8`
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/0c3a8abf-3226-456c-873a-d10650723f3f)
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/c6c7e2ef-076e-4e23-aa33-4706ffc992a5)

**Comment by soxofaan** [comment]
as discussed: check if doing `(cube * 1.0).aggregate_temporal(...`  instead of `cube.aggregate_temporal(...`  can be used as workaround

**Comment by EmileSonneveld** [comment]
That indeed works. Recalculation here:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/bfdf064f-00cf-4d3e-ba76-cf83667276c7)


I still feel this might be a nice thing to fix, as the result values are around the same range as the original values and the result may be of the same cellType

**Comment by soxofaan** [comment]
sure, this has to be fixed, but the good thing is that there is a simple workaround for now

**Comment by jdries** [comment]
may be fixed as side effect of other celltype issues

**Comment by jdries** [comment]
@EmileSonneveld  should be fixed on dev instances. Please try again and reopen if necessary.
