### ISSUE TITLE
OpenEO batch job failed: Exception during Spark execution: an implementation is missing

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#242]
Example job: `j-231129c1874e416da43266d612f91683`
Minimal graph that reproduces this:
```json
{
  "process_graph": {
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "bands": [
          "B03",
          "sunAzimuthAngles"
        ],
        "id": "SENTINEL2_L2A",
        "spatial_extent": {
          "crs": 32630,
          "srs": 32630,
          "east": 278551.21116394224,
          "north": 4829145.746240205,
          "south": 4827235.746240205,
          "west": 276641.21116394224
        },
        "temporal_extent": [
          "2021-01-01",
          "2021-01-02"
        ]
      },
      "result": true
    }
  },
  "parameters": []
}
```
Changing the spatial_extent to different CRS still shows the problem:
```json
{
  "crs": 4326,
  "srs": 4326,
  "east": -5.7428787,
  "north": 43.582377,
  "west": -5.7657222,
  "south": 43.5646292,
}
```

Unclear how this error got introduced. The fix is probably to implement all methods here:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/68143219e6882dffd0d05a46aaf29e530c0b93a5/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/SentinelXMLMetadataRasterSource.scala#L52

**Comment by bossie** [comment]
[org.openeo.geotrellis.layers.NoDataRasterSource](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/3a8622ffc184efd26487a4a858ea6f842ca5ce90/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/layers/NoDataRasterSource.scala) is similar so could be an inspiration.

**Comment by EmileSonneveld** [comment]
The region in question was valid in 2 UTM zones. ...29 and ...30. In Python, `auto_utm_espg` gives a different result compared to the catalog. I made the code handle CRS differences for `SentinelXMLMetadataRasterSource`.
