### ISSUE TITLE
geotiff + netcdf: support writing sub-day files

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#257]
I propose to detect if timestamps have hours and or minutes, and in that case use a more accurate timestamp or resolution.

Here:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/d618910335cb0e5e7d6e00d5903091d410802015/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala#L127

and here:

https://github.com/Open-EO/openeo-geotrellis-extensions/blob/01b67c85f27ff59fde22872a53a13306b79eb6f9/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/netcdf/NetCDFRDDWriter.scala#L130

**Comment by EmileSonneveld** [comment]
I removed the aggregate from https://github.com/Open-EO/openeo-geopyspark-driver/issues/647 to test:
- When exporting as tiff, I indeed got only a date in the name, not hour and minutes.
- When exporting as NetCDF, I got a combination of both samples in the same file:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/da4e8635-ef3b-4b3e-8ed7-cfead1d7f0a3)

**Comment by EmileSonneveld** [comment]
There still seems to be a problem with nodata in `.nc` files
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/d68eeb27-c2a7-42ed-ac9e-f9e72dfda3cf)

**Comment by EmileSonneveld** [comment]
This was implemented for NetCDF, but still need to find a way to implement it for TIFF without performance penalty

**Comment by jdries** [comment]
I pushed the basic solution for writing geotiff per date, ignoring that different date formats will be used if an rdd mixes day and subday timestamps.

**Comment by jdries** [comment]
it works on staging for gtiff, there's also a unit test, so closing this one now
