### ISSUE TITLE
JEP udf callApplyMetadata should change band dimension

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geotrellis-extensions#266]
Currently callApplyMetadata:
- is only able to change the spatial resolution. 
- does not show the band dimension to the user

We want to support:
- Show band dimension to user
  - This requires passing the python metadata to JEP udfs
  - E.g. "bands": {"type": "bands", "values": ["red", "nir"]}
- Show temporal extent of the temporal dimension
  - E.g. "t": {"type": "temporal", extent=("2024-01-01", "2024-01-02")}
- Allow user to change bands dimension
  - This requires passing the metadata back to python
- Pass new step size to python
  -  This requires passing the metadata back to python

**Comment by EmileSonneveld** [comment]
Minimal example to reproduce: https://gist.github.com/JeroenVerstraelen/57847e544374c4eb172e205f8da32f02

**Comment by EmileSonneveld** [comment]
@JeroenVerstraelen in [the example from here](https://github.com/Open-EO/FuseTS/blob/cd3170460f053d2d70b5861d8b38777886b02869/src/fusets/openeo/mogpr_udf.py#L78), the returned array is in dtype `float64`, I had to cast it to `float32` to avoid an error. Do you think openEO should be dealing with it instead? `...transpose(*dims).astype('float32')`

**Comment by EmileSonneveld** [comment]
In the UDF, a `.name` should be added `[openeo.metadata.Band(f\"{x.name}_STD\", None, None) for x in metadata.bands]` (relevant: https://github.com/Open-EO/openeo-api/issues/530 )

After this, the CRS seems to go missing.

**Comment by JanssenBrm** [comment]
Thanks guys, nice work! I got it working on dev using your fixes and sample code (https://github.com/Open-EO/FuseTS/blob/feat/123_mogpr_uncertainties/src/fusets/openeo/mogpr_udf.py#L44-L57). 

Any idea on when this would be available on production? Looking forward!
