### ISSUE TITLE
gaps in SENTINEL2_L2A on CDSE

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-extensions#280]
Internal ref: CDSE-100

Process graph:

```json
{
  "process_graph": {
    "loadcollection1": {
      "process_id": "load_collection",
      "arguments": {
        "bands": [
          "B02",
          "B03",
          "B04",
          "B08"
        ],
        "id": "SENTINEL2_L2A",
        "spatial_extent": {
          "west": -162.2501,
          "east": -161.2879,
          "south": 70.1839,
          "north": 70.3401
        },
        "temporal_extent": [
          "2024-03-24",
          "2024-03-25"
        ]
      }
    },
    "saveresult1": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "loadcollection1"
        },
        "format": "GTiff",
        "options": {}
      },
      "result": true
    }
  }
}
```

Result: [20240324T230529Z_S2.tif.txt](https://github.com/Open-EO/openeo-geotrellis-extensions/files/14917724/20240324T230529Z_S2.tif.txt)

Same process graph on Terrascope looks great; "derived_from" links look the same: [openEO_2024-03-24Z_Terrascope.tif.txt](https://github.com/Open-EO/openeo-geotrellis-extensions/files/14917731/openEO_2024-03-24Z_Terrascope.tif.txt)

**Comment by EmileSonneveld** [comment]
Due to laptop issues, and support, this ticket is still in progress

**Comment by EmileSonneveld** [comment]
Probably unrelated, but tiles have different color tints in result:
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/649f94a0-0279-4fa2-881b-ada094dda07e)

**Comment by jdries** [comment]
@EmileSonneveld  for these different color tints, you may want to link to a visualization of the source product in copernicus browser, to establish whether or not the problem exists also there.
Then next step is to see how these band values actually differ. It doesn't make much sense that openEO would somehow change values within the bands...

**Comment by EmileSonneveld** [comment]
This is deployed on CDSE prod.
Running the job from the user gives a full result.

**Comment by EmileSonneveld** [comment]
Isolated color difference in new issue: https://github.com/Open-EO/openeo-geotrellis-extensions/issues/294
