### ISSUE TITLE
Save_result as COG: option for setting block size

### ISSUE THREAD

**Issue by JorisCod** [Open-EO/openeo-geotrellis-extensions#328]
When creating a COG as a result file, the block size corresponds to the chunk size. Recently, this has been lowered to 128. However, larger blocks size is like 256 x 256 or larger would be better for general use.

Proposal: add a setting for increasing/setting the block size upon creation of the COG.

**Comment by JorisCod** [comment]
@JeroenVerstraelen is it possible to plan this issue for the next sprint? If not, the sprint afterwards is also fine.

**Comment by JeroenVerstraelen** [comment]
- Initial implementation: only for save_asset_per_band.
- Could also be solved by some changes on the LCFM side. We'll have to ask.

cc @VictorVerhaert

**Comment by JorisCod** [comment]
Cfr. https://teams.microsoft.com/l/message/19:2941a270bf8e48a2a8e8a23975051c11@thread.skype/1727873689689?tenantId=9e2777ed-8237-4ab9-9278-2c144d6f6da3&groupId=8c9c739d-2544-4def-8cd4-b65970551b70&parentMessageId=1727873689689&teamName=Unit%20TAP&channelName=openEO-users&createdTime=1727873689689

Enabling asset_per_band results in a COG block size of 256, which should be enough for LCFM for now.

So this issue can be removed from the planning.
