### ISSUE TITLE
load_stac: reading multiband cogs

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#332]
Based on current state of the code (todo's), we should test a few cases of multiband cog, as I expect issues:
 
- loading bands in different order than 'native'
- loading bands from multiple multiband tifs, probably proba-v provides a good example of this case

**Comment by JeroenVerstraelen** [comment]
**Loading bands in different order than 'native' has been checked and works in production:**
I executed both process graphs found [here](https://gist.github.com/JeroenVerstraelen/868e1be44866f32605d7076686f48f59)

And then compared the results using xarray
```
import xarray as xr
import numpy as np
nativeds = xr.open_dataset("nativeorder.nc")
notnativeds = xr.open_dataset("notnativeorder.nc")

np.allclose(nativeds['precipitation-flux'], notnativeds['precipitation-flux'])
np.allclose(nativeds['temperature-mean'], notnativeds['temperature-mean'])
```

**Comment by JeroenVerstraelen** [comment]
The following two process graphs also produce identical results on openeo.vito.be:
https://gist.github.com/JeroenVerstraelen/559c4de20327147b4865d3f472868399

So it seems like loading bands from multiple multiband tiffs works.
