### ISSUE TITLE
Job option for soft errors in data loading

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#34]
We sometimes see errors in data loading that are caused by the underlying service (e.g. sentinelhub) or application (e.g. orfeo toolbox).
A category of these errors only occurs for very specific chunks and dates,
When a user is sampling a lot of data points, or an algorithm aggregates a lot of data, it is not always a problem if 0.1% of chunks are missing. Hence, we may want to have an option to turn hard errors into warnings that perhaps show up in the output metadata.

Relatively urgent because this is now happening in Sentinelhub access for sampling.
Also note that we may first want to do a couple of retries, to avoid errors that are really transient.

**Comment by soxofaan** [comment]
related (but probably not a solution):
when requesting batch job results there is a option "partial" to accept partial results (instead of getting a JobNotFinished error):
see https://github.com/Open-EO/openeo-api/issues/430

**Comment by bossie** [comment]
First iteration:

```python
s1_grd = conn.load_collection('SENTINEL1_GRD')
s1_grd._pg.arguments['featureflags'] = {'soft_errors': True}

data_cube = (s1_grd
             .filter_bands(['VH', 'VV'])
             .filter_bbox(west=488960.0, south=6159880.0, east=491520.0, north=6162440.0, crs="EPSG:32632")
             .filter_temporal(extent=["2016-11-10", "2016-11-10"])
             .sar_backscatter(elevation_model="MAPZEN"))

data_cube.download("/tmp/test_soft_errors.tif")
```

It ignores Sentinel Hub errors and instead logs them to Elasticsearch ("WARN: ignoring soft error...").

**Comment by bossie** [comment]
Replaced "load_collection" feature flag with job_option:

```python
s1_grd = conn.load_collection('SENTINEL1_GRD')

data_cube = (s1_grd
             .filter_bands(['VH', 'VV'])
             .filter_bbox(west=488960.0, south=6159880.0, east=491520.0, north=6162440.0, crs="EPSG:32632")
             .filter_temporal(extent=["2016-11-10", "2016-11-10"])
             .sar_backscatter(elevation_model="MAPZEN"))

data_cube.execute_batch(job_options={'soft-errors': 'true'})
```

This returns successfully without results but with a log in Kibana (including the stack trace):

> ignoring soft error {"error":{"status":400,"reason":"Bad Request","message":"Requested band 'VH' is not present in Sentinel 1 tile 'S1B_EW_GRDM_1SDH_20161110T053134_20161110T053228_002892_004E80_8BC5' returned by criteria specified in `dataFilter` parameter.","code":"RENDERER_S1_MISSING_POLARIZATION"}}

**Comment by bossie** [comment]
TODO: count errors and really fail if there are too many.

**Comment by soxofaan** [comment]
> ```python
> data_cube.execute_batch(job_options={'soft-errors': 'true'})
> ```

I guess `{'soft-errors': True}`   is also valid, or is it really a string @bossie ?

**Comment by bossie** [comment]
Supporting specifying a threshold ratio of errors/requests [0.0, 1.0] as well as real boolean values

Example code:
```python
data_cube.execute_batch(job_options={'soft-errors': True})  # = threshold ratio 1.0 so all errors are ignored/treated as soft
data_cube.execute_batch(job_options={'soft-errors': 0.001})  # job fails if more than 0.1% of requests fail
```

Example logs:
```
ignoring soft error {"error":{"status":400,"reason":"Bad Request","message":"Requested band 'VH' is not present in Sentinel 1 tile 'S1B_EW_GRDM_1SDH_20161110T053134_20161110T053228_002892_004E80_8BC5' returned by criteria specified in `dataFilter` parameter.","code":"RENDERER_S1_MISSING_POLARIZATION"}}; error/request ratio [1/1] 1.0 <= 1.0

propagating hard error {"error":{"status":400,"reason":"Bad Request","message":"Requested band 'VH' is not present in Sentinel 1 tile 'S1B_EW_GRDM_1SDH_20161110T053134_20161110T053228_002892_004E80_8BC5' returned by criteria specified in `dataFilter` parameter.","code":"RENDERER_S1_MISSING_POLARIZATION"}}; error/request ratio [1/1] 1.0 > 0.001
```
