### ISSUE TITLE
Try streaming tiffs to s3

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#347]
This has been tried here: https://github.com/Open-EO/openeo-geotrellis-extensions/issues/199
But was disabled: https://github.com/Open-EO/openeo-geotrellis-extensions/commit/01b67c85f27ff59fde22872a53a13306b79eb6f9#diff-eb0b0fb3836fe17a6e2feaf1496210faf468bfd995d245163cf3876af89626a9L229

We can try again for tiffs with some extra precaution.

**Comment by EmileSonneveld** [comment]
@pvbouwel Would this add TRY_SWIFT_STREAMING to the environment variables on the executors?
https://git.vito.be/projects/TPT/repos/os_creodias_openeo_k8s/browse/kube_resources/applications/openeo/values_cdse-dev.yaml#23

**Comment by pvbouwel** [comment]
Yes, in dev it also shows:
```
❯ k get pod/openeo-geotrellis-1-b0e1ff93d4e4a4ae-exec-12 -o=json | grep -A 1 TRY
                        "name": "TRY_SWIFT_STREAMING",
                        "value": "True"
❯ k get pod/a-3b25aec83f4d4892aba85c554730467d-bd92e693d4ff6cee-exec-2 -o=json | grep -A 1 TRY
                        "name": "GDAL_HTTP_MAX_RETRY",
                        "value": "20"
--
                        "name": "GDAL_HTTP_RETRY_DELAY",
                        "value": "10"
--
                        "name": "TRY_SWIFT_STREAMING",
                        "value": "True"
```
