### ISSUE TITLE
Sentinelhub sampling jobs have long catalog lookup time

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#35]
Sentinelhub sampling jobs for points seem to spend a long time before they actually start processing.
I see a lot of logging about catalog queries. Maybe we can combine a few queries into a single one, or even request such a feature with sentinelhub?

**Comment by bossie** [comment]
A larger page size (the default is 10) might help: https://docs.sentinel-hub.com/api/latest/api/catalog/#pagination

**Comment by bossie** [comment]
Set page size to the maximum of 100.
