### ISSUE TITLE
rate-limiting errors on shub auth

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#40]
Jobs are failing because we do too many authentication requests to sentinelhub.
Tokens are cached, but expiry time is provided by shub, and we divide by two.

https://github.com/Open-EO/openeo-geotrellis-extensions/blob/feature/spark3/geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/AccessTokenCache.scala#L10

Maybe consider waiting longer before evicting token from cache? Retry + backoff seems to be in place already.

What if we just put the token in the syncer? Then it would be central, and executors don't have to request it.

**Comment by jdries** [comment]
@dthiex  What do you guys think about putting the auth token also in the syncer service, is it viable? Or are there alternatives to avoid being rate limited on the authentication?

**Comment by Ardweaden** [comment]
How does refreshing the token work on your side? I believe they typically expire in ~2 hours so it's surprising to me many requests are made.

> What do you guys think about putting the auth token also in the syncer service, is it viable

Well the syncer uses a SH token to fetch the user quotas etc. It refreshes the token 5 minutes before expiry. Yes, it could expose another function e.g. `get_access_token` which the workers would call to get the token.

**Comment by jdries** [comment]
It's still happening, even with only one user running relatively small jobs.
I do see that the jobs themselves take only like 4 minutes, so if the tokens are cached in memory, you get new requests from 50 to 100 workers every 5 minutes.
I'm also wondering if the rate limiting is perhaps imposed on the full API, so also tile requests have impact on rate limiting of auth requests?

In any case, the solution with the syncer might resolve all of this.
@bossie  This is happening in production, any chance you can give it priority?

**Comment by jdries** [comment]
Other option that doesn't involve changing rate limiting guard: broadcasting initial access token from the driver to all executors.
We see these failures already at the very beginning of a job, so that might help. Not sure what will happen upon expiry of course.

**Comment by Ardweaden** [comment]
> I'm also wondering if the rate limiting is perhaps imposed on the full API, so also tile requests have impact on rate limiting of auth requests?

No, they don't affect each other.

------------------

> Other option that doesn't involve changing rate limiting guard: broadcasting initial access token from the driver to all executors. We see these failures already at the very beginning of a job, so that might help. Not sure what will happen upon expiry of course.

It does seem like the proper solution is to have a central entity that keeps a valid token at all times.

**Comment by bossie** [comment]
@Ardweaden: is rate-limiting the auth API a recent change? What are the rate limits exactly?

**Comment by Ardweaden** [comment]
> @Ardweaden: is rate-limiting the auth API a recent change? What are the rate limits exactly?

@bossie Yes, it's a recent change. Currently they stand at 30 requests per second, but they are going to get tightened.

**Comment by bossie** [comment]
@Ardweaden @dthiex: this caught us a bit off-guard; in the short-term, is it possible to make an exception for our account while we make the necessary adjustments?

**Comment by dthiex** [comment]
@bossie I was looked at the statistics of your account and it seems like the recent changes significantly improved the situation. In the last 24h out of 600k requests you hit rate limits only 7x (which is acceptable). 

It's unfortunately for us technically not possible to whitelist single accounts. 

Looking at statistics from e.g. Saturday you had 53.000 token requests within 1 hour, which considering that tokens were cached for 1h (SH caching time for tokens is 2h and you divided by 2) seems like too many and some sort of bug.

If you do more testing and need statistics of the account let me know and I can provide them to you.

**Comment by bossie** [comment]
Fixed by making the syncer persist the auth token and retrieving it in the workers.
