### ISSUE TITLE
record sentinelhub synchronous call usage with accumulator

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#41]
record usage of sentinelhub synchronous queries with an accumulator.
For batch jobs, we would somehow like to publish the final number into the metadata where it can be picked up by the marketplace etl flow.

**Comment by jdries** [comment]
This is the line that needs to be changed:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/feature/spark3/geotrellis-sentinelhub/src/main/scala/org/openeo/geotrellissentinelhub/PyramidFactory.scala#L100
We should not do an estimate, but use info from sentinelhub response header.

**Comment by bossie** [comment]
Doesn't work for all collections yet: https://github.com/openEOPlatform/architecture-docs/issues/226.
