### ISSUE TITLE
openeo-geotrellis-extensions branch management

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geotrellis-extensions#44]
Currently the `feature/spark3` branch is the main branch used in production and there is probably no way back anymore.
There still is a `master` branch (not touched in 5 months) and a `develop` branch (not touched in 2 months).

Can we improve this branching situation so that it is more obvious for humans and tools what the main line is?

**Comment by jdries** [comment]
feature/spark3 is now gone
