### ISSUE TITLE
Try to provide glob based layers through catalog based FileLayerProvider

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#45]
Currently, glob based layers suffer in maintainability because only part of the code is reused from other more well tested classes like FileLayerProvider.
What if we can create a 'Catalog' based on a glob? This would perhaps allow us to reuse most of the infrastructure that we now have for more well tested layers.

**Comment by jdries** [comment]
Current implementation:
org.openeo.geotrellis.layers.AbstractGlobFileLayerProvider

**Comment by jdries** [comment]
new layer setup seems to work, tests still need to be added

**Comment by JeroenVerstraelen** [comment]
The BioPar/HRL-VPP layer cannot be created using a Glob file layer provider. The /data/cel_vol4e/ST/V101/ and /data/cel_vol4e/ST/V102/ directories contain roughly 317344 geotif files which are too many paths to gather and filter through. 

Each path does contain a tileID, e.g. /data/cel_vol4e/ST/V101/25SFD/*, so we could translate the requested bbox into tileIDs first. But this requires more custom catalog work so it would be better if we create a catalog instead.
