### ISSUE TITLE
support authentication for reading remote tiffs

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#53]
Implement a RangeReaderProvider that reads authentication from a config file (e.g. in json)
If the URI hosts matches one of the hosts in the file, the authentication should be configured. In this issue, we want to support only basic auth.
So in the range reader, something like:
val request = Http(url.toString).auth("user","pass")

**Comment by bossie** [comment]
@jdries: do we have an endpoint to test this against?

**Comment by jdries** [comment]
Yes, the Terrascope catalog itself. If you query it without an 'accessedFrom' parameter, it will return https links that require auth.
https://services.terrascope.be/catalogue/products?collection=urn%3Aeop%3AVITO%3ATERRASCOPE_S2_LAI_V2&start=2020-01-05T00%3A00%3A00&end=2020-01-15T00%3A00%3A00&bbox=-180.00,0.00,180.00,90.00

We can start with basic auth, but Terrascope is moving to OIDC for that as well. Not sure how easy it will be to support both?

**Comment by bossie** [comment]
Can use my own Terrascope credentials to test.

**Comment by bossie** [comment]
CustomizableHttpRangeReaderProvider will grab basic credentials from a JSON file that looks like this:

```json
{
  "services.terrascope.be": {
    "username": "vdboschj-terrascope",
    "password": "???"
  }
}

```

The location of this file defaults to "./http_credentials.json" and can be overridden by specifying the system property "http.credentials.file". If no such file exists, CustomizableHttpRangeReaderProvider will log a warning and proceed without authentication.

Tested with https://services.terrascope.be/download/Sentinel2/LAI_V2/2020/01/05/S2A_20200105T071301_39RVH_LAI_V200/20M/S2A_20200105T071301_39RVH_LAI_20M_V200.tif

**Comment by bossie** [comment]
As discussed: performance of this implementation will dictate whether we will implement OIDC authentication as well.

**Comment by bossie** [comment]
Tested sync as well as in a batch job by:

1. publishing a mock STAC item online with a single asset that points to Basic auth protected https://services.terrascope.be/download/Sentinel2/LAI_V2/2020/01/05/S2A_20200105T071301_39RVH_LAI_V200/20M/S2A_20200105T071301_39RVH_LAI_20M_V200.tif
2. putting a mock STAC collection online with 1) as the single item
3. doing a load_result of 2)
