### ISSUE TITLE
Assertion error floating types

### ISSUE THREAD

**Issue by Bart92** [Open-EO/openeo-geotrellis-extensions#56]
Hi all,

When I use array_modify in which I try to set a band to a normal float (43000.)  I get the following error as json is not able to verify how many bits the float is:

openeo.rest.OpenEoApiError: [500] Internal: Server error: assertion failed: Band 120 cell type does not match, float64 != float32 (ref: 42bb35a5-6012-4143-b0dd-99850f779a75)

**Comment by jdries** [comment]
@Bart92  can you verify if this error still occurs?

**Comment by Bart92** [comment]
I have tried to run with both 43000. and 43000 now and both are succesful, so it seems to be solved 💯
