### ISSUE TITLE
Performance: high cost of determining keys per RasterSource

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#67]
We spend a lot of time retrieving extent of raster sources, only to determine the available spatial keys.
If extent and crs can be provided by STAC metadata, this becomes a lot less, as determining spatial keys is fairly simple.

Catalogs, like the one from creo, provide the geometry in lat lon coordinates. If we convert it to native crs, we should have a quite accurate footprint.

**Comment by jdries** [comment]
Example of bottleneck occuring:
{code}
com.azavea.gdal.GDALWarp.get_transform(Native Method)
geotrellis.raster.gdal.GDALDataset$.getTransform$extension1(GDALDataset.scala:173)
geotrellis.raster.gdal.GDALDataset$.rasterExtent$extension1(GDALDataset.scala:198)
geotrellis.raster.gdal.GDALRasterSource.gridExtent$lzycompute(GDALRasterSource.scala:93) => holding Monitor(geotrellis.raster.gdal.GDALRasterSource@94701147})
geotrellis.raster.gdal.GDALRasterSource.gridExtent(GDALRasterSource.scala:93)
org.openeo.geotrellis.layers.BandCompositeRasterSource.$anonfun$gridExtent$1(FileLayerProvider.scala:50)
org.openeo.geotrellis.layers.BandCompositeRasterSource$$Lambda$735/0x0000000840717c40.apply(Unknown Source)
app//scala.Option.getOrElse(Option.scala:189)
org.openeo.geotrellis.layers.BandCompositeRasterSource.gridExtent(FileLayerProvider.scala:49)
geotrellis.layer.LayoutTileSource.<init>(LayoutTileSource.scala:34)
geotrellis.layer.LayoutTileSource$.apply(LayoutTileSource.scala:186)
org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$rasterSourceRDD$1(FileLayerProvider.scala:185)
org.openeo.geotrellis.layers.FileLayerProvider$$$Lambda$700/0x00000008406ee040.apply(Unknown Source)
{code}

**Comment by jdries** [comment]
As it turns out, we can also determine spatial keys from lat lon bounding box, which is available in all catalog metadata.
This should allow us to come up with the full set of spacetime keys without touching any image file.

**Comment by bossie** [comment]
I think the current implementation needs some refining because it seems to at least have an impact on the testBIOMASS integration test.

When run locally, the Spark UI shows me it's the evaluation of the SpaceTimeKeys RDD for a 180 day AgEra5 collection that it can't get past ("distinct"):

```
active:

org.apache.spark.rdd.RDD.distinct(RDD.scala:470)
org.openeo.geotrelliscommon.DatacubeSupport$.createPartitioner(DatacubeSupport.scala:126)
org.openeo.geotrellis.layers.FileLayerProvider$.org$openeo$geotrellis$layers$FileLayerProvider$$tileSourcesToDataCube(FileLayerProvider.scala:255)
org.openeo.geotrellis.layers.FileLayerProvider.readMultibandTileLayer(FileLayerProvider.scala:573)
org.openeo.geotrellis.file.Sentinel2PyramidFactory.datacube(Sentinel2PyramidFactory.scala:150)
org.openeo.geotrellis.file.Sentinel2PyramidFactory.datacube_seq(Sentinel2PyramidFactory.scala:129)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:282)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
py4j.ClientServerConnection.run(ClientServerConnection.java:106)
java.lang.Thread.run(Thread.java:750)

pending:

org.apache.spark.rdd.RDD.countApproxDistinct(RDD.scala:1369)
org.openeo.geotrelliscommon.DatacubeSupport$.createPartitioner(DatacubeSupport.scala:127)
org.openeo.geotrellis.layers.FileLayerProvider$.org$openeo$geotrellis$layers$FileLayerProvider$$tileSourcesToDataCube(FileLayerProvider.scala:255)
org.openeo.geotrellis.layers.FileLayerProvider.readMultibandTileLayer(FileLayerProvider.scala:573)
org.openeo.geotrellis.file.Sentinel2PyramidFactory.datacube(Sentinel2PyramidFactory.scala:150)
org.openeo.geotrellis.file.Sentinel2PyramidFactory.datacube_seq(Sentinel2PyramidFactory.scala:129)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
py4j.Gateway.invoke(Gateway.java:282)
py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
py4j.commands.CallCommand.execute(CallCommand.java:79)
py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
py4j.ClientServerConnection.run(ClientServerConnection.java:106)
java.lang.Thread.run(Thread.java:750)
```
