### ISSUE TITLE
stripes in netcdf

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#68]
As reported by user, saving 300m NDVI CGLS to netcdf has artifacts. Saving to GTiff is reported to be correct.

![image](https://user-images.githubusercontent.com/5937096/182122692-829094c6-46d1-4c63-85cf-21b58b39ab7b.png)

**Comment by cajmdebie** [comment]
These artifacts also occur with the 1km imagery and relate to writing the last lines & columns of empty tiles (quite randomly).  Note that the values in the empy tiles differ from the 'novalues' elsewhere.

**Comment by soxofaan** [comment]
possibly related: https://discuss.eodc.eu/t/sentinel1-grd-missing-pixels/412/4 (however at the moment I fail to reproduce the issue on my end)

**Comment by jdries** [comment]
fix and test committed, should appear on openeo-dev
the gridBoundsFor method apparently treats the south/east edge of the provided extent as exclusive, which actually means a line of pixels can be dropped
