### ISSUE TITLE
Image-shifts through bbox,  filter_spatial, or spatial_extent

### ISSUE THREAD

**Issue by cajmdebie** [Open-EO/openeo-geotrellis-extensions#69]
When applying through OPENEO bbox, filter_spatial, or spatial_extent, the most top-left selected pixel (of 1km and 300m imagery!) shifts to the edge of the specified box or defined spacial extent. When extracting using OPENEO an area-of-interest, selected pixcels MUST however actually remain exactly where they were originally placed. When defining a boundary that coincides with pixel-centroids, that always leads to half a pixel shift while the user cannot predict what the first top-left pixel will be (there are 4 candidates!!). See below an example of a half-pixel (500m!!!) shift:

![Clip1](https://user-images.githubusercontent.com/68096252/182553506-f81d5634-1902-4880-a26e-7b98d36ac44f.jpg)

**Comment by cajmdebie** [comment]
At 16Dec my findings remain:

Data example of two extents, where the center-of-pixel of a 1km top-left pixel = 25.000000, -15.383929

A. Use exact corner-of-corners of required pixels:

{'east': 33.29910714314813,
 'west': 24.995535714565385,
 'north': -15.379464285692597,
 'south': -22.64732142854809}

B. Use with half a 333m pixel (0.5/336) extra window-size on all sides:
{'east': 33.30059523838622,
 'west': 24.99404761932729,
 'north': -15.377976190454502,
 'south': -22.648809523786184}

Then the Corner-of-Corner of the top-left-pixel becomes:
Result A: 24.99553571, -15.37946429 <---- correct placing of top-left pixel
Result B: 24.99404762, -15.37797619 <---- image has indeed shifted 0.5/336 degrees!

and the Center-of-Pixel  of the top-left-pixel becomes:
Result A: 25.00000000, -15.38392857 <---- correct placing of top-left pixel
Result B: 24.99851191, -15.38244048 <---- image has indeed shifted 0.5/336 degrees

**Comment by jdries** [comment]
Also happens with worldcover. Proposed solution: if datacube extension has the extent set, and the target crs is the same as source crs, we can try to align the user-provided extent to the one of the dataset. 
This approach only works if the collection does not mix resolutions, or is in UTM.

**Comment by jdries** [comment]
weird, seems like this one got closed automaticaly by a github bot?! 
Anyway, I'm actively testing a solution.

**Comment by jdries** [comment]
I now fixed a lot of metadata to enable the feature that should improve the alignment, will appear on openeo-dev soon. Closing this one already, to reopen if still seeing the issues in a few days.
