### ISSUE TITLE
Report Sentinelhub features in metadata

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#70]
For Terrascope collections, the batch job metadata now stores a link to the original products that were used to generate the result.
The 'derived-from' rel type should be used for this.

Terrascope doesn't use real links yet, but rather an identifier, this is also possible in the absence of decent links, e.g. :
urn:eop:VITO:TERRASCOPE_S2_TOC_V2:S2B_20200211T111109_30TUM_TOC_V200

The code in FileLayerProvider that does this looks like this:
`BatchJobMetadataTracker.tracker("").addInputProducts(openSearchCollectionId,overlappingFeatures.map(_.id).asJava)`

**Comment by EmileSonneveld** [comment]
When running the following:
```python
cube = eoconn.load_collection(
    "TERRASCOPE_S2_TOC_V2",
    bands=["B03", "B04"],
    temporal_extent=["2020-05-01", "2020-05-10"]
)

cube = cube.filter_spatial(input_geojson)
out_format = "GTIFF"
job = cube.create_job(title="Sentinel2",
                      description="Sentinel-2 test",
                      out_format=out_format,
                      sample_by_feature=True
                      )
job.start_and_wait()
job.get_results().download_files("output")
```
I get:
```JavaScript
"links": [
        {
            "href": "urn:eop:VITO:TERRASCOPE_S2_TOC_V2:S2A_20200507T104031_31UGS_TOC_V200",
            "rel": "derived_from",
            "title": "Derived from urn:eop:VITO:TERRASCOPE_S2_TOC_V2:S2A_20200507T104031_31UGS_TOC_V200"
        },
```

href is only an ID here. I don't see an URL that refers to a certain product in Terrascope. Closest I see is the `file://` href that is returned by the [catalogue/products/...](https://services.terrascope.be/catalogue/products?collection=urn%3Aeop%3AVITO%3ATERRASCOPE_S2_TOC_V2&bbox=6.42%2C51.03%2C6.54%2C51.11&sortKeys=title&startIndex=1&accessedFrom=MEP&clientId=&start=2020-05-01T00%3A00%3A00Z&end=2020-05-11T23%3A59%3A59.999999999Z) API. But that refers to a certain band in a product and is probably not what we would expect from a href.
 ```JavaScript
{
  "length": 191091152,
  "href": "file:///data/MTDA/TERRASCOPE_Sentinel2/TOC_V2/2020/05/07/S2A_20200507T104031_31UGS_TOC_V200/S2A_20200507T104031_31UGS_TOC-B04_10M_V200.tif",
  "type": "image/tiff",
  "title": "TOC-B04_10M"
},
```

@jdries Is there an other other URL that can be used? Or is this something that should be added in the Terrascope API?

**Comment by jdries** [comment]
you can ignore that one:  this issue is about sentinelhub based collections.
FYI: when we convert terrascope collections to using STAC instead of opensearch, we can use the 'self' link which is strongly recommended in that spec:
https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#relation-types

**Comment by jdries** [comment]
Example of a 'self' link in stac:
https://services.terrascope.be/stac/collections/urn:eop:VITO:TERRASCOPE_S2_TOC_V2/items/urn:eop:VITO:TERRASCOPE_S2_TOC_V2:S2A_20150704T101006_32TML_TOC_V200

**Comment by EmileSonneveld** [comment]
After this fix, the output of
```JS
cube = eoconn.load_collection(
    "SENTINEL1_GRD",
    bands=["VV"],
    temporal_extent=["2020-05-01", "2020-05-10"]
)
```
changed from:
```json
    "links": [
        {
            "href": "S1B_IW_GRDH_1SDV_20200503T054951_20200503T055016_021413_028A65_D648",
            "rel": "derived_from",
            "title": "Derived from S1B_IW_GRDH_1SDV_20200503T054951_20200503T055016_021413_028A65_D648"
        },
```
to:
```json
    "links": [
        {
            "href": "https://services.sentinel-hub.com/api/v1/catalog/collections/sentinel-1-grd/items/S1B_IW_GRDH_1SDV_20200503T054951_20200503T055016_021413_028A65_D648",
            "rel": "derived_from",
            "title": "Derived from https://services.sentinel-hub.com/api/v1/catalog/collections/sentinel-1-grd/items/S1B_IW_GRDH_1SDV_20200503T054951_20200503T055016_021413_028A65_D648"
        },
```
@jdries Does that look as intended?

**Comment by jdries** [comment]
Yes, this is what we want.
A detail is that the "title" would be more readable if we would just show the product id (like it was), rather than the url, which is already encoded in the href anyway. I'm however not sure if the product id is readily available? (In this case you could parse it from the link, but that is not generally true.)

**Comment by EmileSonneveld** [comment]
It is possible to extend  `BatchJobMetadataTracker.addInputProducts(String collection, List<String> productIds)` to save ids and URLs. This function is used in `openeo-geotrellis-extensions` and `openeo-geopyspark-driver`

**Comment by jdries** [comment]
indeed, or maybe create an overloaded version for backwards compatibility? But maybe just create a new issue for that, as this one seems to be fixed as intended.

**Comment by EmileSonneveld** [comment]
I'll fix it now, with the overload it seems safe

**Comment by EmileSonneveld** [comment]
Also had MR in other repo: https://github.com/Open-EO/openeo-geopyspark-driver/pull/366
