### ISSUE TITLE
Using provider:backend = vito constructs wrong SH requests

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-geotrellis-extensions#73]
I believe the problem is that that provider:backend gets passed to SH and we don't know that to do with this as it's no allowed query extension.

## PG to reproduce
```
cube = connection.load_collection(
    "SENTINEL2_L2A_SENTINELHUB",
    spatial_extent={"west": 13.876, "south": 46.274, "east": 13.888, "north": 46.278},
    temporal_extent=["2022-05-01", "2022-07-31"],
    bands=["B04", "B08"], properties={"provider:backend":lambda v: v =="vito"}
)
```

## Response when trying to download the data
`OpenEoApiError: [500] Internal: Failed to process synchronously on backend vito: OpenEoApiError('[500] Internal: Server error: Sentinel Hub returned an error\nresponse: HTTP/1.1 400 Bad Request with body: {"code":400,"description":"Querying is not supported on property \'provider:backend\'. Possible properties are \'eo:cloud_cover\'."}\nrequest: POST https://services.sentinel-hub.com/api/v1/catalog/search with body: \n{\n  "datetime": "2022-05-01T00:00:00Z/2022-07-31T23:59:59.999999999Z",\n  "collections": ["sentinel-2-l2a"],\n  "query": {"provider:backend":{"eq":"vito"}},\n  "intersects": {"type":"Polygon","coordinates":[[[13.876,46.274],[13.876,46.278],[13.888,46.278],[13.888,46.27400000000001],[13.876,46.274]]]},\n  "limit": 100,\n  "next": null\n} (ref: r-786b0bfdab9f4c21b98e5969bc90927f)') (ref: r-d312db0ade094dba99a89d7e73ccb496)`

**Comment by bossie** [comment]
Looks like a duplicate of https://github.com/Open-EO/openeo-aggregator/issues/49,  @soxofaan ?

**Comment by dthiex** [comment]
Indeed, didn't see this when checking for already existing issues. Closing
