### ISSUE TITLE
avoid resample_cube_spatial in mask and merge_cubes

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#96]
resample_cube_spatial is an important source of process graph complexity, and results in decreased performance.
We now require users to almost always do this, where in fact cubes are pretty much aligned already.
We can easily add a check, and automatically align the right hand side cube to the left hand side both in mask and merge_cubes.

**Comment by soxofaan** [comment]
FYI: there is interest to standardize this behavior in the official process specs: https://github.com/Open-EO/openeo-processes/issues/402
